name             'neo4j'
maintainer       'Julian Tescher'
maintainer_email 'jatescher@gmail.com'
license          'MIT'
description      'Installs/Configures Neo4j'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.1'
depends          'apt', '~> 1.9.2'
depends          'java', '~> 1.10.0'
depends          'zookeeper', '~> 1.1.0'